algoritmo "Calcular o dobro e o triplo"

//Declaração de Variáveis
var

   numero, dobro, triplo: real

// Seção de Comandos
inicio

//Entrada de dados
escreva("Insira um número para saber o dobro e o triplo do mesmo: ")
leia(numero)

//Calculando o dobro e o triplo
dobro <- numero*2
triplo <- numero*3

//Saída de dados
escreval("")
escreval("O dobro de", numero, " é:", dobro)
escreval("O triplo de", numero, " é:", triplo)

fimalgoritmo
