algoritmo "Algoritmo para calcular area de um triangulo"

//Declaração de Variáveis
var

base: real
altura: real
area: real

inicio

//Entrada de Dados
escreval("Digite a base:")
leia(base)

escreval("Digite a altura:")
leia(altura)

//Calculando valor da área utilizando os dados inseridos pelo usuário
area <- (base*altura)/2

//Saída de dados
escreval("A área do triângulo é: ", area)

fimalgoritmo
