algoritmo "Verificar se o número é ímpar ou par"

//Declaração de Variáveis
var

   numero: inteiro

// Seção de Comandos
inicio

   //Entrada de dados
   escreva("Informe um número pra saber se o mesmo é ímpar ou par: ")
   leia(numero)

   //Estrutura condicional que verifica se o número é ímpar ou par
   se (numero%2)=0 entao
      escreval("")
      escreval("O número é Par")
   senao
      escreval("")
      escreval("O número é Ímpar")
   fimse

fimalgoritmo
