algoritmo "Calculando valor da área de um retângulo"

//Declaração de Variáveis
var

lado1: real
lado2: real
area: real

inicio

//Entrada de Dados
escreva("Digite o lado 1: ")
leia(lado1)

escreva("Digite o lado 2: ")
leia(lado2)

//Calculando valor da área utilizando os dados inseridos pelo usuário
area <- lado1*lado2

//Saída de dados
escreval("")
escreval("A área do retângulo é: ", area)

fimalgoritmo
